# Generated by Django 5.1.4 on 2024-12-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_alter_note_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notesapp.favorites'),
        ),
    ]
