# Generated by Django 5.1.4 on 2024-12-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_alter_note_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
